name: my_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - openmpi
  - mpi4py
  - tensorboard
  - matplotlib
  - cryptography
  - numpy
  - pandas
  - pillow
  - requests
  - seaborn
  - pytorch
  - torchvision
  - cpuonly
  - scipy
  - pyyaml
  - tqdm
  - psutil
  - protobuf
  - ipython
  - pip
